In [6]:
import numpy as np
a=[]
for i in range(6):
    a.append(i)

myarray = np.array(a)
myarray

array([0, 1, 2, 3, 4, 5])

In [15]:
import numpy as np
a=[[1,2,3,4],[5,6,7,8]]


myarray = np.array(a)

print(myarray[1][1])
print(myarray)
print("shape of array = ",myarray.shape)
print("Dimension of array is = ",myarray.ndim)

6
[[1 2 3 4]
 [5 6 7 8]]
shape of array =  (2, 4)
Dimension of array is =  2
