In [2]:
import numpy as np
a=[]
for i in range(10):
    a.append(np.random.randint(1,10)
             
print("Total array is = ",myarray)
print("String Slicing array is = ",myarray[2:5])

Total array is =  [6 5 6 9 6 9 1 6 1 7]
String Slicing array is =  [6 9 6]


In [9]:
import numpy as np
a=[]
for i in range(10):
    a.append(np.random.randint(1,10))
    
myarray=np.array(a)


myarray = myarray.reshape(2,5)
print("THe reshaping array is = \n",myarray)
myarray = myarray.reshape(5,2)
print("THe reshaping array is = \n",myarray)

THe reshaping array is = 
 [[5 6 1 4 2]
 [4 9 2 5 4]]
THe reshaping array is = 
 [[5 6]
 [1 4]
 [2 4]
 [9 2]
 [5 4]]
