In [4]:
import numpy as np
array = np.zeros(4)
print("one dimensionls array is for all zeros = ",array)

array1 = np.zeros((2,3))
print("2 dimensionals array is for all zeros = ",array1)

one dimensionls array is =  [0. 0. 0. 0.]
2 dimensionals array is =  [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
import numpy as np
array1 = np.ones(5)
print("one dimensional array for all 1 is  = ",array1)

array2 = np.ones((2,4))
print("2 dimensional array for all 2 is  = ",array2)

one dimensional array for all 1 is  =  [1. 1. 1. 1. 1.]
2 dimensional array for all 2 is  =  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
import numpy as np
array1 = np.eye(5)
print("its create the 5 rows and 5 column matrix with diagonal 1 is  = ",array1)

array2 = np.eye(2,4)
print("2 dimensional array for 2 rows and 4 column with all diagonal 1 is  = \n",array2)

its create the 5 rows and 5 column matrix with diagonal 1 is  =  [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
2 dimensional array for 2 rows and 4 column with all diagonal 1 is  = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [15]:
import numpy as np
array1 = np.diag([5,3,4,5,2])
print("its create the diagonal of the 4 * 4 with specific values",array1)

its create the diagonal of the 4 * 4 with specific values [[5 0 0 0 0]
 [0 3 0 0 0]
 [0 0 4 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]


In [19]:
import numpy as np
array1 = np.random.randint(5,15,2)
print("its create two random numbers from 5 to 14",array1)

its create two random numbers from 5 to 14 [12  7]


In [20]:
import numpy as np
array1 = np.random.rand(5)
print("its create 5 random numbers from 0 to 1",array1) 

its create 5 random numbers from 0 to 1 [0.61513762 0.27149237 0.39388501 0.83170068 0.53908777]


In [21]:
import numpy as np
array1 = np.random.rand(5)
print("its create 5 random numbers from 0 to 1",array1) 

its create 5 random numbers from 0 to 1 [0.57707834 0.29175136 0.1562113  0.13022363 0.8110236 ]


In [22]:
import numpy as np
array1 = np.random.randn(5)
print("its create 5 random numbers from near to 0 ",array1)

its create 5 random numbers from near to 0  [ 0.97529105 -1.10633573 -2.15475141  1.73949229 -0.60381076]
