In [16]:
import numpy as np
matrix=[[3,5,7,7,3],[1,7,3,5,3],[8,3,8,7,3]]
arr = np.array(matrix)

slicing = arr[1: , 1:4]
slicing[:]=0
print("This is view array when we change in array also change in main array = \n",arr)



This is view array when we change in array also change in main array = 
 [[3 5 7 7 3]
 [1 0 0 0 3]
 [8 0 0 0 3]]


In [18]:
import numpy as np
matrix=[[3,5,7,7,3],[1,7,3,5,3],[8,3,8,7,3]]
arr = np.array(matrix)
slicing1 = arr[1: , 1:4].copy()
slicing1[:]=0
print("This is copy array when we change in array the main arrya does not change = \n",arr)

This is view array when we change in array also change in main array =  [[3 5 7 7 3]
 [1 7 3 5 3]
 [8 3 8 7 3]]
